### PR TITLE
feat(portals): using live updates

### PR DESCRIPTION
**Pull request by eric-horodyski**

### CODE REVIEW

**Comment by jon-ionic** [comment]
This looks great! One thing I'm a bit unclear about (and this just may be my ignorance about the prior training leading up to this section)- is the reader meant to be able to use the provided Appflow PAT with the `portals sync` command? Or are they creating their own app in Appflow and pushing the web app up to it/using their own PAT to pull it down?

If the former, the token no longer seems to work.

**Comment by eric-horodyski** [comment]
> This looks great! One thing I'm a bit unclear about (and this just may be my ignorance about the prior training leading up to this section)- is the reader meant to be able to use the provided Appflow PAT with the `portals sync` command? Or are they creating their own app in Appflow and pushing the web app up to it/using their own PAT to pull it down?
> 
> If the former, the token no longer seems to work.

Yes, they are supposed to use the PAT...but it was deleted from my account...what the heck

**Comment by eric-horodyski** [comment]
@jon-ionic Do you mind re-reviewing? I tokenized the PAT. Should anyone deploy over my work...we'll just have to get notified by customers and I can rollback.

**Comment by jon-ionic** [comment]
Oh, clever! This looks good to me.

**Review by jon-ionic — APPROVED** [review]

**Pull request merged**
